可以直接使用astype转换数组元素的数据类型
```
# 使用astype将整形数组转化为浮点数组
int_arr = np.array([1, 2, 3, 4])
print(int_arr.dtype)
float_arr = int_arr.astype(np.float32)
print(float_arr.dtype)

# int64
# float32
```
如果你有一个数组，里面的元素都是表达数字含义的字符串，也可以通过astype将字符串转换为数字
```
# 使用astype将字符串类型转化为float类型
import numpy as np
nums_str = np.array(['1.25', '-5.67'], dtype= np.string_)
print(nums_str.astype(float))
print(nums_str.astype(np.float64))

# [ 1.25 -5.67]
# [ 1.25 -5.67]
```
**数组运算**

numpy可以直接操作数组进行算术，任何在两个等尺寸数组之间的算术操作都应用了逐元素操作的方式
```
# 对数组整体进行加减
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print()
arr_mult = arr * arr
print(arr_mult)
print()
arr_sub = arr - arr
print(arr_sub)
print()
print(arr ** 2)
print()
print(1/arr)
print()

# [[1 2 3]
#  [4 5 6]]

# [[ 1  4  9]
#  [16 25 36]]

# [[0 0 0]
#  [0 0 0]]

# [[ 1  4  9]
#  [16 25 36]]

# [[1.         0.5        0.33333333]
#  [0.25       0.2        0.16666667]]
```

同尺寸数组之间的比较，会产生一个布尔值数组
```
# 同尺寸数据进行比较
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_mult = arr * arr
print(arr < arr_mult)

# [[False  True  True]
#  [ True  True  True]]
```


In [ ]:
# 同尺寸数据进行比较
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_mult = arr * arr
print(arr < arr_mult)

# [[False  True  True]
#  [ True  True  True]]

In [ ]:
# 对数组整体进行加减
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print()
arr_mult = arr * arr
print(arr_mult)
print()
arr_sub = arr - arr
print(arr_sub)
print()
print(arr ** 2)
print()
print(1/arr)
print()

# [[1 2 3]
#  [4 5 6]]

# [[ 1  4  9]
#  [16 25 36]]

# [[0 0 0]
#  [0 0 0]]

# [[ 1  4  9]
#  [16 25 36]]

# [[1.         0.5        0.33333333]
#  [0.25       0.2        0.16666667]]

In [ ]:
# 使用astype将整形数组转化为浮点数组
int_arr = np.array([1, 2, 3, 4])
print(int_arr.dtype)
float_arr = int_arr.astype(np.float32)
print(float_arr.dtype)

# int64
# float32

In [ ]:
# 使用astype将字符串类型转化为float类型
import numpy as np
nums_str = np.array(['1.25', '-5.67'], dtype= np.string_)
print(nums_str.astype(float))
print(nums_str.astype(np.float64))

# [ 1.25 -5.67]
# [ 1.25 -5.67]